// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivwgdzadvaiowcyrxaed.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2d2dkemFkdmFpb3djeXJ4YWVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNTQyMjUsImV4cCI6MjA2MDYzMDIyNX0.8KlhXr8_SecGn-k7OElBtkq1L_YmwWCl97iLn4SllbE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);